apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo
      app.kubernetes.io/component: backend
  replicas: {{ .Values.db.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: {{ .Values.db.containers.name }} 
        image: {{ .Values.db.containers.image}}
        args: {{ toYaml .args |  }} ## v possibile errore
        resources:
        ports:
        - containerPort: {{ .Values.db.containers.port }}
        volumeMounts:
        - name: volume
          mountPath: {{ .Values.db.containers.volume.path }}
      volumes:
      - name: volume
        persistentVolumeClaim:
           claimName: mongo-pvc

