apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  labels: 
    app: mongo-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.resources.storageSize }}
