apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: guestbook
      app.kubernetes.io/component: frontend
  replicas: {{ .Values.app.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guestbook
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: {{ .Values.app.container.name }}
        image: {{ .Values.app.container.image }}
        env:
        - name: {{ .Values.env.name }}
          value: {{ .Values.env.value }} 
        ports:
        - containerPort: {{ .Values.app.container.port }}

