##values for MongoDB 

db:
  name: mongo
  replicaCount: 1
  containers:
    name: mongo
    image: mongo:4.2
    args: 
      - --bind_ip
      - 0.0.0.0
    port: 27017
    volume:
      path: /data/db

service:
  port: 27017
  type: ClusterIP
  targetPort : 27017

pvc:
  resources:
    storageSize: 1Gi
