##values for MongoDB 

db:
  name: mongo
  replicaCount: 2
  containers:
    name: mongo
    image: mongo:4.2
    args: 
      - --bind_ip
      - 0.0.0.0
    port: 27017
    volume:
      path: /data/db

service:
  port: 27017
  type: ClusterIP
